GROUP=io.github.runalia
VERSION_NAME=1.0.0
POM_ARTIFACT_ID=android-hosted-payments

# Maven Central
mavenCentralUsername=oheT4v
mavenCentralPassword=SFDFdgN98sdqI5MSY3C3uBjbEHVrrcik4
# GPG

signing.gnupg.keyName=79D901EBEF439F53
signing.gnupg.passphrase=Password@123
signing.gnupg.useLegacyGpg=false

android.useAndroidX=true
android.enableJetifier=true